env:
  browser: true

extends:
  - airbnb-base
  - prettier

parserOptions:
  ecmaVersion: 2017
  sourceType: module

plugins:
  ['prettier']

rules:
  no-unused-expressions: warn
  prefer-template: warn
  prettier/prettier: ['error']